language: scala
scala: 2.11.5
jdk: oraclejdk8

env:
    - PROJECT=recfun
    - PROJECT=funsets
    - PROJECT=objsets
    - PROJECT=patmat
    - PROJECT=forcomp
	

script:
    - cd $PROJECT && sbt ++$TRAVIS_SCALA_VERSION test
